from pathlib import Path

import pandas as pd
from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware


# ============================================================
# CONFIGURATION
# ============================================================

BASE_DIR = Path(__file__).resolve().parent
RISK_DATA_PATH = BASE_DIR / "data" / "project_risk_results.csv"


# ============================================================
# FASTAPI APPLICATION
# ============================================================

app = FastAPI(
    title="PRISM AI API",
    description=(
        "AI-powered risk intelligence API for MPLADS "
        "prototype project monitoring."
    ),
    version="0.3.0",
)


# ============================================================
# CORS
# ============================================================

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Prototype only
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ============================================================
# DATA LOADING
# ============================================================

def load_risk_data() -> pd.DataFrame:
    """
    Load project-level risk results generated by
    the PRISM AI risk engine.
    """

    if not RISK_DATA_PATH.exists():
        raise FileNotFoundError(
            f"Risk data file not found: {RISK_DATA_PATH}"
        )

    df = pd.read_csv(RISK_DATA_PATH)

    return df


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def find_column(
    df: pd.DataFrame,
    candidates: list[str],
):
    """
    Return the first matching column from candidates.
    """

    for column in candidates:
        if column in df.columns:
            return column

    return None


def normalize_text(value) -> str:
    """
    Convert a value into a clean lowercase string.
    """

    if pd.isna(value):
        return ""

    return str(value).strip().lower()


def safe_float(value, default=None):
    """
    Safely convert a value to float.
    """

    try:
        if pd.isna(value):
            return default

        return float(value)

    except (TypeError, ValueError):
        return default


def clean_number(value, decimals=2):
    """
    Safely round a number for JSON responses.
    """

    number = safe_float(value)

    if number is None:
        return None

    return round(number, decimals)


# ============================================================
# HEALTH CHECK
# ============================================================

@app.get("/")
def root():
    return {
        "system": "PRISM AI",
        "message": "PRISM AI API is running",
        "status": "online",
    }


@app.get("/health")
def health():
    return {
        "status": "healthy",
        "service": "PRISM AI API",
    }


# ============================================================
# DASHBOARD SUMMARY
# ============================================================

@app.get("/dashboard/summary")
def dashboard_summary():
    """
    Return summary statistics for the dashboard.
    """

    try:
        df = load_risk_data()

    except FileNotFoundError as error:
        raise HTTPException(
            status_code=500,
            detail=str(error),
        )

    if "risk_level" not in df.columns:
        raise HTTPException(
            status_code=500,
            detail="Column 'risk_level' not found in risk data.",
        )

    risk_counts = (
        df["risk_level"]
        .astype(str)
        .str.strip()
        .value_counts()
        .to_dict()
    )

    return {
        "total_projects": int(len(df)),
        "high_risk": int(
            risk_counts.get("High", 0)
        ),
        "medium_risk": int(
            risk_counts.get("Medium", 0)
        ),
        "low_risk": int(
            risk_counts.get("Low", 0)
        ),
    }


# ============================================================
# ALL PROJECTS WITH FILTERS
# ============================================================

@app.get("/projects")
def get_projects(
    risk_level: str | None = Query(
        default=None,
        description="Filter by Low, Medium, or High",
    ),
    category: str | None = Query(
        default=None,
        description="Filter by project category",
    ),
    state: str | None = Query(
        default=None,
        description="Filter by state",
    ),
    district: str | None = Query(
        default=None,
        description="Filter by district",
    ),
    status: str | None = Query(
        default=None,
        description="Filter by project status",
    ),
    limit: int = Query(
        default=100,
        ge=1,
        le=500,
    ),
):
    """
    Return project records with optional filters.
    """

    try:
        df = load_risk_data()

    except FileNotFoundError as error:
        raise HTTPException(
            status_code=500,
            detail=str(error),
        )

    # --------------------------------------------------------
    # Risk-level filter
    # --------------------------------------------------------

    if risk_level:

        valid_levels = [
            "Low",
            "Medium",
            "High",
        ]

        matched_level = next(
            (
                level
                for level in valid_levels
                if normalize_text(level)
                == normalize_text(risk_level)
            ),
            None,
        )

        if matched_level is None:
            raise HTTPException(
                status_code=400,
                detail=(
                    "risk_level must be Low, Medium, or High"
                ),
            )

        if "risk_level" not in df.columns:
            raise HTTPException(
                status_code=500,
                detail="Column 'risk_level' not found.",
            )

        df = df[
            df["risk_level"]
            .astype(str)
            .str.strip()
            == matched_level
        ]

    # --------------------------------------------------------
    # Category filter
    # --------------------------------------------------------

    if category:

        category_column = find_column(
            df,
            [
                "category",
                "Category",
            ],
        )

        if category_column:
            df = df[
                df[category_column]
                .apply(normalize_text)
                == normalize_text(category)
            ]

    # --------------------------------------------------------
    # State filter
    # --------------------------------------------------------

    if state:

        state_column = find_column(
            df,
            [
                "state",
                "State",
            ],
        )

        if state_column:
            df = df[
                df[state_column]
                .apply(normalize_text)
                == normalize_text(state)
            ]

    # --------------------------------------------------------
    # District filter
    # --------------------------------------------------------

    if district:

        district_column = find_column(
            df,
            [
                "district",
                "District",
            ],
        )

        if district_column:
            df = df[
                df[district_column]
                .apply(normalize_text)
                == normalize_text(district)
            ]

    # --------------------------------------------------------
    # Status filter
    # --------------------------------------------------------

    if status:

        status_column = find_column(
            df,
            [
                "current_status",
                "Current_Status",
                "current status",
                "status",
                "Status",
            ],
        )

        if status_column:
            df = df[
                df[status_column]
                .apply(normalize_text)
                == normalize_text(status)
            ]

    # --------------------------------------------------------
    # Sort by risk
    # --------------------------------------------------------

    if "risk_score" in df.columns:

        df["risk_score"] = pd.to_numeric(
            df["risk_score"],
            errors="coerce",
        ).fillna(0)

        df = df.sort_values(
            by="risk_score",
            ascending=False,
        )

    # --------------------------------------------------------
    # Apply limit
    # --------------------------------------------------------

    df = df.head(limit)

    # --------------------------------------------------------
    # JSON records
    # --------------------------------------------------------

    records = df.to_dict(
        orient="records"
    )

    return {
        "count": len(records),
        "projects": records,
    }


# ============================================================
# HIGH-RISK PROJECTS
# ============================================================

@app.get("/projects/high-risk")
def get_high_risk_projects(
    limit: int = Query(
        default=50,
        ge=1,
        le=500,
    ),
):
    """
    Return projects requiring priority review.
    """

    try:
        df = load_risk_data()

    except FileNotFoundError as error:
        raise HTTPException(
            status_code=500,
            detail=str(error),
        )

    if "risk_level" not in df.columns:
        raise HTTPException(
            status_code=500,
            detail="Column 'risk_level' not found.",
        )

    high_risk = df[
        df["risk_level"]
        .astype(str)
        .str.strip()
        == "High"
    ].copy()

    if "risk_score" in high_risk.columns:

        high_risk["risk_score"] = pd.to_numeric(
            high_risk["risk_score"],
            errors="coerce",
        ).fillna(0)

        high_risk = high_risk.sort_values(
            "risk_score",
            ascending=False,
        )

    high_risk = high_risk.head(limit)

    return {
        "count": len(high_risk),
        "projects": high_risk.to_dict(
            orient="records"
        ),
    }


# ============================================================
# FILTER OPTIONS
# ============================================================

@app.get("/projects/filter-options")
def get_filter_options():
    """
    Return unique values for dashboard filter dropdowns.
    """

    try:
        df = load_risk_data()

    except FileNotFoundError as error:
        raise HTTPException(
            status_code=500,
            detail=str(error),
        )

    def unique_values(
        candidates: list[str],
    ):

        column = find_column(
            df,
            candidates,
        )

        if not column:
            return []

        values = (
            df[column]
            .dropna()
            .astype(str)
            .str.strip()
        )

        values = [
            value
            for value in values.unique().tolist()
            if value
            and value.lower() != "nan"
            and value.lower() != "unknown"
        ]

        return sorted(values)

    return {
        "states": unique_values(
            [
                "state",
                "State",
            ]
        ),

        "districts": unique_values(
            [
                "district",
                "District",
            ]
        ),

        "categories": unique_values(
            [
                "category",
                "Category",
            ]
        ),

        "statuses": unique_values(
            [
                "current_status",
                "Current_Status",
                "current status",
                "status",
                "Status",
            ]
        ),

        "risk_levels": [
            "All",
            "High",
            "Medium",
            "Low",
        ],
    }


# ============================================================
# DASHBOARD ANALYTICS
# ============================================================

@app.get("/dashboard/analytics")
def dashboard_analytics():
    """
    Return aggregated analytics for the dashboard.

    Includes:
        - Risk distribution
        - Project status distribution
        - Category distribution
        - Risk-signal counts
        - Top categories by average risk
        - Overall average risk
    """

    try:
        df = load_risk_data()

    except FileNotFoundError as error:
        raise HTTPException(
            status_code=500,
            detail=str(error),
        )

    # --------------------------------------------------------
    # Risk distribution
    # --------------------------------------------------------

    risk_distribution = {
        "High": 0,
        "Medium": 0,
        "Low": 0,
    }

    if "risk_level" in df.columns:

        risk_counts = (
            df["risk_level"]
            .astype(str)
            .str.strip()
            .value_counts()
            .to_dict()
        )

        for level in risk_distribution:

            risk_distribution[level] = int(
                risk_counts.get(
                    level,
                    0,
                )
            )

    # --------------------------------------------------------
    # Status distribution
    # --------------------------------------------------------

    status_distribution = {}

    status_column = find_column(
        df,
        [
            "current_status",
            "Current_Status",
            "current status",
            "status",
            "Status",
        ],
    )

    if status_column:

        status_counts = (
            df[status_column]
            .fillna("Unknown")
            .astype(str)
            .str.strip()
            .replace("", "Unknown")
            .value_counts()
            .to_dict()
        )

        status_distribution = {
            str(key): int(value)
            for key, value
            in status_counts.items()
        }

    # --------------------------------------------------------
    # Category distribution
    # --------------------------------------------------------

    category_distribution = {}

    category_column = find_column(
        df,
        [
            "category",
            "Category",
        ],
    )

    if category_column:

        category_counts = (
            df[category_column]
            .fillna("Unknown")
            .astype(str)
            .str.strip()
            .replace("", "Unknown")
            .value_counts()
            .to_dict()
        )

        category_distribution = {
            str(key): int(value)
            for key, value
            in category_counts.items()
        }

    # --------------------------------------------------------
    # Risk signal counts
    # --------------------------------------------------------

    signal_counts = {
        "Cost Anomaly": 0,
        "Execution Delay": 0,
        "Similar / Duplicate Work": 0,
        "Unusual Spending": 0,
    }

    # Cost
    if "cost_score" in df.columns:

        numeric = pd.to_numeric(
            df["cost_score"],
            errors="coerce",
        ).fillna(0)

        signal_counts["Cost Anomaly"] = int(
            (numeric > 0).sum()
        )

    elif "sanction_overrun_pct" in df.columns:

        numeric = pd.to_numeric(
            df["sanction_overrun_pct"],
            errors="coerce",
        ).fillna(0)

        signal_counts["Cost Anomaly"] = int(
            (numeric > 0).sum()
        )

    # Delay
    if "delay_score" in df.columns:

        numeric = pd.to_numeric(
            df["delay_score"],
            errors="coerce",
        ).fillna(0)

        signal_counts["Execution Delay"] = int(
            (numeric > 0).sum()
        )

    elif "delay_pct" in df.columns:

        numeric = pd.to_numeric(
            df["delay_pct"],
            errors="coerce",
        ).fillna(0)

        signal_counts["Execution Delay"] = int(
            (numeric > 0).sum()
        )

    # Duplicate
    if "duplicate_score" in df.columns:

        numeric = pd.to_numeric(
            df["duplicate_score"],
            errors="coerce",
        ).fillna(0)

        signal_counts[
            "Similar / Duplicate Work"
        ] = int(
            (numeric > 0).sum()
        )

    elif "max_similarity_pct" in df.columns:

        numeric = pd.to_numeric(
            df["max_similarity_pct"],
            errors="coerce",
        ).fillna(0)

        signal_counts[
            "Similar / Duplicate Work"
        ] = int(
            (numeric > 0).sum()
        )

    # Spending
    if "spending_score" in df.columns:

        numeric = pd.to_numeric(
            df["spending_score"],
            errors="coerce",
        ).fillna(0)

        signal_counts["Unusual Spending"] = int(
            (numeric > 0).sum()
        )

    elif "category_zscore" in df.columns:

        numeric = pd.to_numeric(
            df["category_zscore"],
            errors="coerce",
        ).fillna(0)

        signal_counts["Unusual Spending"] = int(
            (numeric.abs() > 0).sum()
        )

    # --------------------------------------------------------
    # Top categories by average risk
    # --------------------------------------------------------

    category_risk = []

    if (
        category_column
        and "risk_score" in df.columns
    ):

        temp = df.copy()

        temp["risk_score"] = pd.to_numeric(
            temp["risk_score"],
            errors="coerce",
        ).fillna(0)

        grouped = (
            temp
            .groupby(category_column)
            ["risk_score"]
            .agg(
                project_count="count",
                average_risk="mean",
            )
            .reset_index()
            .sort_values(
                "average_risk",
                ascending=False,
            )
        )

        for _, row in grouped.head(10).iterrows():

            category_risk.append(
                {
                    "category": str(
                        row[category_column]
                    ),

                    "project_count": int(
                        row["project_count"]
                    ),

                    "average_risk": round(
                        float(
                            row["average_risk"]
                        ),
                        2,
                    ),
                }
            )

    # --------------------------------------------------------
    # Average risk
    # --------------------------------------------------------

    average_risk = 0.0

    if "risk_score" in df.columns:

        numeric = pd.to_numeric(
            df["risk_score"],
            errors="coerce",
        ).fillna(0)

        average_risk = round(
            float(numeric.mean()),
            2,
        )

    return {
        "total_projects": int(
            len(df)
        ),

        "average_risk_score": average_risk,

        "risk_distribution":
            risk_distribution,

        "status_distribution":
            status_distribution,

        "category_distribution":
            category_distribution,

        "signal_counts":
            signal_counts,

        "top_categories_by_risk":
            category_risk,
    }


# ============================================================
# COMPARABLE PROJECTS
# ============================================================

@app.get("/projects/{project_id}/comparables")
def get_comparable_projects(
    project_id: str,
    limit: int = Query(
        default=5,
        ge=1,
        le=20,
    ),
):
    """
    Return projects that are most comparable to
    the selected project.

    Comparison factors:
        - Same category
        - Same district
        - Same state
        - Similar project amount
    """

    try:
        df = load_risk_data()

    except FileNotFoundError as error:
        raise HTTPException(
            status_code=500,
            detail=str(error),
        )

    if "project_id" not in df.columns:
        raise HTTPException(
            status_code=500,
            detail="Column 'project_id' not found.",
        )

    # --------------------------------------------------------
    # Find selected project
    # --------------------------------------------------------

    matches = df[
        df["project_id"]
        .astype(str)
        .str.upper()
        == project_id.upper()
    ]

    if matches.empty:
        raise HTTPException(
            status_code=404,
            detail=(
                f"Project '{project_id}' not found"
            ),
        )

    selected = matches.iloc[0]

    # --------------------------------------------------------
    # Detect useful columns
    # --------------------------------------------------------

    category_column = find_column(
        df,
        [
            "category",
            "Category",
        ],
    )

    district_column = find_column(
        df,
        [
            "district",
            "District",
        ],
    )

    state_column = find_column(
        df,
        [
            "state",
            "State",
        ],
    )

    amount_column = find_column(
        df,
        [
            "sanctioned_amount_lakh",
            "sanctioned_amount",
            "Sanctioned_Amount",
            "expenditure_lakh",
            "expenditure",
        ],
    )

    # --------------------------------------------------------
    # Candidate projects
    # --------------------------------------------------------

    candidates = df[
        df["project_id"]
        .astype(str)
        .str.upper()
        != project_id.upper()
    ].copy()

    if candidates.empty:
        return {
            "project_id": project_id,
            "count": 0,
            "comparables": [],
        }

    # --------------------------------------------------------
    # Selected attributes
    # --------------------------------------------------------

    selected_category = (
        normalize_text(
            selected[category_column]
        )
        if category_column
        else ""
    )

    selected_district = (
        normalize_text(
            selected[district_column]
        )
        if district_column
        else ""
    )

    selected_state = (
        normalize_text(
            selected[state_column]
        )
        if state_column
        else ""
    )

    # --------------------------------------------------------
    # Comparison score
    # --------------------------------------------------------

    candidates["_comparison_score"] = 0.0

    # Same category = 50 points
    if (
        category_column
        and selected_category
    ):

        candidates["_comparison_score"] += (
            candidates[category_column]
            .apply(normalize_text)
            .eq(selected_category)
            .astype(float)
            * 50
        )

    # Same district = 25 points
    if (
        district_column
        and selected_district
    ):

        candidates["_comparison_score"] += (
            candidates[district_column]
            .apply(normalize_text)
            .eq(selected_district)
            .astype(float)
            * 25
        )

    # Same state = 10 points
    if (
        state_column
        and selected_state
    ):

        candidates["_comparison_score"] += (
            candidates[state_column]
            .apply(normalize_text)
            .eq(selected_state)
            .astype(float)
            * 10
        )

    # --------------------------------------------------------
    # Amount similarity = up to 15 points
    # --------------------------------------------------------

    if amount_column:

        selected_amount = safe_float(
            selected[amount_column]
        )

        candidates["_amount_value"] = pd.to_numeric(
            candidates[amount_column],
            errors="coerce",
        )

        if selected_amount is not None:

            max_amount = max(
                abs(selected_amount),
                1,
            )

            amount_difference = (
                candidates["_amount_value"]
                .sub(selected_amount)
                .abs()
            )

            amount_similarity = (
                1
                - (
                    amount_difference
                    / max_amount
                )
            ).clip(
                lower=0,
                upper=1,
            )

            candidates["_comparison_score"] += (
                amount_similarity * 15
            )

    # --------------------------------------------------------
    # Sort
    # --------------------------------------------------------

    candidates = candidates.sort_values(
        "_comparison_score",
        ascending=False,
    )

    candidates = candidates.head(limit)

    # --------------------------------------------------------
    # Prepare response
    # --------------------------------------------------------

    output = []

    for _, row in candidates.iterrows():

        record = {
            "project_id": str(
                row.get(
                    "project_id",
                    "Unknown",
                )
            ),

            "category": (
                str(
                    row.get(
                        category_column,
                        "Unknown",
                    )
                )
                if category_column
                else "Unknown"
            ),

            "district": (
                str(
                    row.get(
                        district_column,
                        "Unknown",
                    )
                )
                if district_column
                else "Unknown"
            ),

            "state": (
                str(
                    row.get(
                        state_column,
                        "Unknown",
                    )
                )
                if state_column
                else "Unknown"
            ),

            "risk_score": clean_number(
                row.get(
                    "risk_score"
                )
            ),

            "risk_level": str(
                row.get(
                    "risk_level",
                    "Unknown",
                )
            ),

            "sanctioned_amount_lakh":
                clean_number(
                    row.get(
                        "sanctioned_amount_lakh"
                    )
                ),

            "expenditure_lakh":
                clean_number(
                    row.get(
                        "expenditure_lakh"
                    )
                ),

            "comparison_score":
                clean_number(
                    row.get(
                        "_comparison_score"
                    )
                ),
        }

        output.append(record)

    return {
        "project_id": project_id,
        "count": len(output),
        "comparables": output,
    }


# ============================================================
# SINGLE PROJECT
# ============================================================

@app.get("/projects/{project_id}")
def get_project(project_id: str):
    """
    Return detailed risk information for one project.
    """

    try:
        df = load_risk_data()

    except FileNotFoundError as error:
        raise HTTPException(
            status_code=500,
            detail=str(error),
        )

    if "project_id" not in df.columns:
        raise HTTPException(
            status_code=500,
            detail="Column 'project_id' not found.",
        )

    match = df[
        df["project_id"]
        .astype(str)
        .str.upper()
        == project_id.upper()
    ]

    if match.empty:
        raise HTTPException(
            status_code=404,
            detail=(
                f"Project '{project_id}' not found"
            ),
        )

    project = match.iloc[0].to_dict()

    return project