from pathlib import Path

import pandas as pd
from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware


# ============================================================
# CONFIGURATION
# ============================================================

BASE_DIR = Path(__file__).resolve().parent
RISK_DATA_PATH = BASE_DIR / "data" / "project_risk_results.csv"


# ============================================================
# FASTAPI APPLICATION
# ============================================================

app = FastAPI(
    title="LADS AI API",
    description=(
        "AI-powered risk intelligence API for MPLADS "
        "prototype project monitoring."
    ),
    version="0.1.0",
)


# ============================================================
# CORS
# ============================================================
# Allows our future React frontend to communicate with FastAPI
# while developing locally.

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Prototype only
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ============================================================
# DATA LOADING
# ============================================================

def load_risk_data() -> pd.DataFrame:
    """
    Load the project-level results generated by the LADS AI
    Risk Engine.
    """

    if not RISK_DATA_PATH.exists():
        raise FileNotFoundError(
            f"Risk data file not found: {RISK_DATA_PATH}"
        )

    df = pd.read_csv(RISK_DATA_PATH)

    return df


# ============================================================
# HEALTH CHECK
# ============================================================

@app.get("/")
def root():
    return {
        "system": "LADS AI",
        "message": "LADS AI API is running",
        "status": "online",
    }


@app.get("/health")
def health():
    return {
        "status": "healthy",
        "service": "LADS AI API",
    }


# ============================================================
# DASHBOARD SUMMARY
# ============================================================

@app.get("/dashboard/summary")
def dashboard_summary():
    """
    Return summary statistics for the dashboard.
    """

    try:
        df = load_risk_data()

    except FileNotFoundError as error:
        raise HTTPException(
            status_code=500,
            detail=str(error)
        )

    risk_counts = (
        df["risk_level"]
        .value_counts()
        .to_dict()
    )

    return {
        "total_projects": int(len(df)),
        "high_risk": int(risk_counts.get("High", 0)),
        "medium_risk": int(risk_counts.get("Medium", 0)),
        "low_risk": int(risk_counts.get("Low", 0)),
    }


# ============================================================
# ALL PROJECTS
# ============================================================

@app.get("/projects")
def get_projects(
    risk_level: str | None = Query(
        default=None,
        description="Filter by Low, Medium, or High"
    ),
    category: str | None = Query(
        default=None,
        description="Filter by project category"
    ),
    limit: int = Query(
        default=100,
        ge=1,
        le=500
    ),
):
    """
    Return project records with optional filters.
    """

    try:
        df = load_risk_data()

    except FileNotFoundError as error:
        raise HTTPException(
            status_code=500,
            detail=str(error)
        )

    # --------------------------------------------------------
    # Risk filter
    # --------------------------------------------------------

    if risk_level:

        valid_levels = [
            "Low",
            "Medium",
            "High"
        ]

        matched_level = next(
            (
                level
                for level in valid_levels
                if level.lower() == risk_level.lower()
            ),
            None
        )

        if matched_level is None:
            raise HTTPException(
                status_code=400,
                detail=(
                    "risk_level must be Low, Medium, or High"
                )
            )

        df = df[
            df["risk_level"] == matched_level
        ]

    # --------------------------------------------------------
    # Category filter
    # --------------------------------------------------------

    if category:

        df = df[
            df["category"].astype(str).str.lower()
            == category.lower()
        ]

    # --------------------------------------------------------
    # Sort highest risk first
    # --------------------------------------------------------

    df = df.sort_values(
        "risk_score",
        ascending=False
    )

    # --------------------------------------------------------
    # Limit results
    # --------------------------------------------------------

    df = df.head(limit)

    # --------------------------------------------------------
    # Convert safely to JSON-compatible records
    # --------------------------------------------------------

    records = df.to_dict(orient="records")

    return {
        "count": len(records),
        "projects": records,
    }


# ============================================================
# HIGH-RISK PROJECTS
# ============================================================

@app.get("/projects/high-risk")
def get_high_risk_projects(
    limit: int = Query(
        default=50,
        ge=1,
        le=500
    )
):
    """
    Return projects requiring priority review.
    """

    try:
        df = load_risk_data()

    except FileNotFoundError as error:
        raise HTTPException(
            status_code=500,
            detail=str(error)
        )

    high_risk = df[
        df["risk_level"] == "High"
    ].sort_values(
        "risk_score",
        ascending=False
    ).head(limit)

    return {
        "count": len(high_risk),
        "projects": high_risk.to_dict(
            orient="records"
        ),
    }


# ============================================================
# SINGLE PROJECT
# ============================================================

@app.get("/projects/{project_id}")
def get_project(project_id: str):
    """
    Return detailed risk information for one project.
    """

    try:
        df = load_risk_data()

    except FileNotFoundError as error:
        raise HTTPException(
            status_code=500,
            detail=str(error)
        )

    match = df[
        df["project_id"].astype(str).str.upper()
        == project_id.upper()
    ]

    if match.empty:
        raise HTTPException(
            status_code=404,
            detail=f"Project '{project_id}' not found"
        )

    project = match.iloc[0].to_dict()

    return project